### ISSUE TITLE
Версия laravel

### ISSUE THREAD

**Issue by levantez** [movemoveapp/laravel-dadata#13]
Добрый день. 

В laravel 5.8 пакет illuminate/support такой же версии 5.8

для `composer require movemoveapp/laravel-dadata` - `requires illuminate/support ^8.8.0`

Получается ваш пакет встанет только на laravel 8. Просто в readme написано что делать для версий ниже 5.5 , а по факту оно туда и не установится.

**Comment by pipisco** [comment]
Добрый день! Спасибо вам за issue. Дайте мне немного времени, чтобы разобраться в вашей задачей.

**Comment by pipisco** [comment]
Да. По всей видимости, версия 5.8 не будет поддерживаться в данном пакете. Прошу прощения.
