### ISSUE TITLE
Поддержка PHP 8.0

### ISSUE THREAD

**Issue by mnogokotin** [movemoveapp/laravel-dadata#15]
Привет, нужно добавить поддержку PHP 8.0 )

**Comment by evgtretyakov** [comment]
я так установил:
composer require movemoveapp/laravel-dadata --ignore-platform-reqs

**Comment by mnogokotin** [comment]
а я форкнул, сделаю чуть позже пр )

**Comment by Vadim-vg** [comment]
При установке получил следующую ошибку:

_[InvalidArgumentException]                                                                                                         
  Package movemoveapp/laravel-dadata has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version:  
    - movemoveapp/laravel-dadata requires php ^7.3 which does not match your installed version 8.0.7.                                
    - movemoveapp/laravel-dadata requires guzzlehttp/guzzle ^7.0 but it is not present._

Мои параметры:
PHP Version 8.0.7
Composer version 2.1-dev
Laravel Framework 8.29.0
- guzzlehttp/guzzle version 7.2.0

Параметры --ignore-platform-reqs помогли для тестирования подойдёт.
Но хотелось бы закрыть эти вопросы в продакшн

**Comment by pipisco** [comment]
@Vadim-vg спасибо за замечание. Учту.

**Comment by koptelovav** [comment]
Планируется ли добавить поддержку php8?

**Comment by perkovandrey** [comment]
Поддержка php8 очень нужна! 
Запускать композер каждый раз с --ignore-platform-reqs только потому что установлен dadata пакет, такое себе(

**Comment by mnogokotin** [comment]
> Поддержка php8 очень нужна! Запускать композер каждый раз с --ignore-platform-reqs только потому что установлен dadata пакет, такое себе(

да все, проект мертв )

**Comment by perkovandrey** [comment]
> 
Видимо да =(

**Comment by denis660** [comment]
Сделали форк пакета, так как этот умер
https://github.com/sushi-market/laravel-dadata
поддержка последнего Laravel 9 и PHP 8

**Comment by pipisco** [comment]
Ребят! Всем привет! 
Прошу прощения за то, что так долго не отвечал. Сейчас все сделаю. Ветка живая!

**Comment by pipisco** [comment]
Поддержка PHP8 и Laravel 9.x выполнена. Коллеги, прошу прощения за задержку. 
https://github.com/movemoveapp/laravel-dadata/releases/tag/v1.0.9
